[project]
name = "managercode"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "black>=25.1.0",
    "matplotlib>=3.10.3",
    "scipy>=1.15.3",
]
