base_model: Qwen/Qwen3-8B
model_type: AutoModelForCausalLM
tokenizer_type: AutoTokenizer

# Remove deprecated flags
load_in_8bit: false
load_in_4bit: false
strict: false

# Update quantization config to use BitsAndBytesConfig format
quantization_config:
  bnb_4bit_compute_dtype: "float16"
  bnb_4bit_use_double_quant: true
  bnb_4bit_quant_type: "nf4"
  load_in_4bit: true

# Add LoRA configuration
adapter: lora
lora_r: 16
lora_alpha: 32
lora_dropout: 0.05
lora_target_modules:
  - q_proj
  - k_proj
  - v_proj
  - o_proj
  - gate_proj
  - up_proj
  - down_proj

datasets:
  - path: fine-tune/data.jsonl
    type: alpaca
    field_instruction: instruction
    field_input: input
    field_output: output
    train_on_inputs: false
    prompt_style: alpaca

dataset_prepared_path: fine-tune/prepared
val_set_size: 0.1
output_dir: fine-tune/output

sequence_len: 2048

# Training parameters
learning_rate: 2.0e-5
micro_batch_size: 1
gradient_accumulation_steps: 16
num_train_epochs: 3
warmup_ratio: 0.03
optim: adamw_torch
weight_decay: 0.1
gradient_checkpointing: true
seed: 42

# Logging and saving
logging_steps: 10
save_strategy: steps
save_steps: 100
eval_steps: 100
save_total_limit: 3

# Precision settings
fp16: false
bf16: false
tf32: false

# Optimizer settings
adam_beta1: 0.9
adam_beta2: 0.999
adam_epsilon: 1e-8
max_grad_norm: 1.0

# Accelerate configuration
accelerate_config:
  num_processes: 1
  num_machines: 1
  mixed_precision: "no"
  dynamo_backend: "no" 
